name: Deploy React to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ← CAMBIA A 20
          
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Debug - Show built files
        run: |
          cat dist/index.html | head -10
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # ← Vite usa 'dist', no 'build'
          force_orphan: true
